# Generated by Django 4.2.7 on 2024-01-22 12:57

from django.db import migrations, models
import tips.models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='tip_media',
            field=models.FileField(blank=True, upload_to=tips.models.tip_media_path),
        ),
    ]
