# Generated by Django 4.2.7 on 2024-02-02 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0003_hospital_road_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='hospital.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_chat_room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.hospitalchatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='chat_messag_created_b6b51c_idx'), models.Index(fields=['sender'], name='chat_messag_sender__c4389c_idx'), models.Index(fields=['chat_room'], name='chat_messag_chat_ro_acf3ae_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hospitalchatroom',
            index=models.Index(fields=['-created_at'], name='chat_hospit_created_de1991_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalchatroom',
            index=models.Index(fields=['hospital'], name='chat_hospit_hospita_0e7222_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalchatroom',
            index=models.Index(fields=['user'], name='chat_hospit_user_id_92d279_idx'),
        ),
    ]
